### ISSUE TITLE
Grafana v7.3.1 does not work with the sidecar injector

### ISSUE THREAD

**Issue by ericandrewmeadows** [Talend/vault-sidecar-injector#42]
**Describe the issue**
Injection does not work for `grafana/grafana:7.3.1`, or `grafana/grafana:7.3.1-ubuntu` images

**To Reproduce**
Attempt to inject as `env`.

**Expected behavior**
As with `ubuntu` base images, I would expect it to inject as secrets.

**Screenshots**

**Environment (please complete the following information):**
 - OS: `alpine:3.12`
 - Kubernetes
    - cluster: GKE
    - 1.16
 - Vault Server
    - version
 - Vault Sidecar Injector
    - chart version: 4.1.0

**Additional context**
It appears to show a nonsensical error message, which is unexpected.

**Comment by asaintsever** [comment]
Hi @ericandrewmeadows and thanks for the report.

To help me reproducing your issue, could you provide:
- the Kubernetes manifest you use to deploy your workload (especially the Vault Sidecar Injector annotations as well as the command attribute for your grafana container)
- the name of the env vars used for secrets injection
- the error message/log you got

Thank you.

**Comment by asaintsever** [comment]
Hey @ericandrewmeadows, I created my own config using `grafana/grafana:7.3.1` image and was able to successfully inject a secret as a Grafana env.

I decided to pick the `GF_SECURITY_ADMIN_USER` env as an example in order to change the default security user (which is `admin`) and to have this env injected as a secret by Vault Sidecar Injector.

To do that, steps are:

1. Update the Vault server test script to provision the env var as a secret (you can also use Vault UI or your own scripts to do that as long as you use the same Vault role and policy as me):

```init-dev-vault-server.sh
## init-dev-vault-server.sh (from deploy/vault folder)
[...]
# Just add your env var here
${VAULT_POD} "VAULT_TOKEN=root vault kv put secret/test/test-app-svc ttl=10s GF_SECURITY_ADMIN_USER=Robin"
```

2. Run the Vault server provisioning script (you must have a running Vault server of course, follow instructions in documentation if needed): `deploy/vault/init-dev-vault-server.sh`

3. Now deploy following custom Grafana manifest (with Vault Sidecar Injector annotations):

**Note: as stated in [documentation](https://github.com/Talend/vault-sidecar-injector/blob/master/doc/announcements/Injecting-secrets-in-env.md), you must set the `command` attribute for your workload. Here, if you look at Grafana image, you'll see that the entrypoint is set to `/run.sh` so you have to set the `command` attribute using the same value**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      com.talend.application: test
      com.talend.service: test-app-svc
  template:
    metadata:
      annotations:
        sidecar.vault.talend.org/inject: "true"
        sidecar.vault.talend.org/secrets-injection-method: "env"
        sidecar.vault.talend.org/secrets-type: "static" # env vars injection only support static secrets
      labels:
        com.talend.application: test
        com.talend.service: test-app-svc
    spec:
      containers:
      - image: grafana/grafana:7.3.1
        name: grafana
        command:  # you MUST set 'command' for env injection to work (look at ENTRYPOINT & CMD from Grafana Dockerfile to get values to set here)
          - "/run.sh"
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http
  selector:
    com.talend.application: test
    com.talend.service: test-app-svc
```

4. Then wait for initialization of Grafana pod and look at the log:

```log
[...]
t=2020-11-17T20:38:24+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=Robin"
[...]
```

As you can see our secret has been successfully injected as an env var and taken into account according to Grafana's log.

Open your browser and authenticate on Grafana using login `Robin` (pwd: `admin`).

Everything works as intended. As you didn't share your manifest I can't say what was your issue but it may be that you forgot to set the `command` attribute.

I will consider this issue resolved without more details regarding your issue. Thanks.
